from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List
from datetime import datetime
from enum import Enum


class ActionType(str, Enum):
    """Types of playbook actions"""
    BLOCK_IP = "block_ip"
    RESET_PASSWORD = "reset_password"
    DISABLE_ACCOUNT = "disable_account"
    ISOLATE_HOST = "isolate_host"
    NOTIFY_ADMIN = "notify_admin"
    COLLECT_EVIDENCE = "collect_evidence"
    CUSTOM = "custom"


class ActionStatus(str, Enum):
    """Status of a playbook action"""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"


class PlaybookAction(BaseModel):
    """
    Individual action within a playbook.
    
    Represents a single mitigation step that can be:
    - Generated by AI based on alert analysis
    - Reviewed and approved by humans
    - Executed automatically or manually
    """
    
    action_id: str = Field(..., description="Unique action identifier")
    action_type: ActionType = Field(..., description="Type of action to perform")
    
    # Action Details
    title: str = Field(..., description="Human-readable action title")
    description: str = Field(..., description="Detailed description of what this action does")
    
    # Execution Parameters
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Action-specific parameters (e.g., {'ip': '1.2.3.4'} for block_ip)"
    )
    
    # Status Tracking
    status: ActionStatus = Field(default=ActionStatus.PENDING, description="Current action status")
    
    # Risk Assessment
    risk_level: str = Field(..., description="Risk level: low, medium, high")
    requires_approval: bool = Field(default=True, description="Whether human approval is required")
    
    # Execution Metadata
    created_at: datetime = Field(..., description="When the action was created")
    approved_at: Optional[datetime] = Field(None, description="When the action was approved")
    approved_by: Optional[str] = Field(None, description="Who approved the action")
    executed_at: Optional[datetime] = Field(None, description="When the action was executed")
    completed_at: Optional[datetime] = Field(None, description="When the action completed")
    
    # Results
    result: Optional[Dict[str, Any]] = Field(None, description="Execution result details")
    error: Optional[str] = Field(None, description="Error message if action failed")
    
    class Config:
        json_schema_extra = {
            "example": {
                "action_id": "action-123",
                "action_type": "block_ip",
                "title": "Block suspicious IP address",
                "description": "Block IP 203.0.113.45 at firewall level due to brute force attack",
                "parameters": {
                    "ip": "203.0.113.45",
                    "duration_hours": 24,
                    "firewall_rule_name": "block_bruteforce_203_0_113_45"
                },
                "status": "pending",
                "risk_level": "medium",
                "requires_approval": True,
                "created_at": "2026-02-15T12:05:00Z"
            }
        }


class Playbook(BaseModel):
    """
    Playbook model representing a collection of response actions.
    
    This schema is designed for:
    - AI to generate based on alert investigation
    - Humans to review and approve
    - System to execute with proper safeguards
    """
    
    # Core Playbook Fields
    playbook_id: str = Field(..., description="Unique playbook identifier")
    created_at: datetime = Field(..., description="When the playbook was created")
    updated_at: datetime = Field(..., description="Last update timestamp")
    
    # Playbook Metadata
    name: str = Field(..., description="Playbook name")
    description: str = Field(..., description="What this playbook aims to accomplish")
    
    # Associated Alert
    alert_id: str = Field(..., description="Alert that triggered this playbook")
    
    # Actions
    actions: List[PlaybookAction] = Field(..., description="List of actions in this playbook")
    
    # Overall Status
    status: str = Field(default="draft", description="Playbook status: draft, approved, executing, completed")
    
    # Approval Workflow
    requires_approval: bool = Field(default=True, description="Whether playbook requires human approval")
    approved_at: Optional[datetime] = Field(None, description="When the playbook was approved")
    approved_by: Optional[str] = Field(None, description="Who approved the playbook")
    
    # Execution Tracking
    execution_started_at: Optional[datetime] = Field(None, description="When execution started")
    execution_completed_at: Optional[datetime] = Field(None, description="When execution completed")
    
    # AI Generation Metadata (for transparency)
    generated_by: str = Field(default="system", description="What generated this playbook (e.g., 'ai_agent', 'manual')")
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="AI confidence in recommendations")
    
    # Results Summary
    total_actions: int = Field(..., description="Total number of actions")
    completed_actions: int = Field(default=0, description="Number of completed actions")
    failed_actions: int = Field(default=0, description="Number of failed actions")
    
    # Metadata
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata for extensibility"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "playbook_id": "playbook-550e8400",
                "created_at": "2026-02-15T12:05:00Z",
                "updated_at": "2026-02-15T12:05:00Z",
                "name": "Mitigate Brute Force Attack",
                "description": "Response playbook for detected brute force authentication attack",
                "alert_id": "alert-550e8400",
                "actions": [
                    {
                        "action_id": "action-1",
                        "action_type": "block_ip",
                        "title": "Block attacker IP",
                        "description": "Block source IP at firewall",
                        "parameters": {"ip": "203.0.113.45"},
                        "status": "pending",
                        "risk_level": "medium",
                        "requires_approval": True,
                        "created_at": "2026-02-15T12:05:00Z"
                    }
                ],
                "status": "draft",
                "requires_approval": True,
                "generated_by": "ai_agent",
                "confidence_score": 0.89,
                "total_actions": 1,
                "completed_actions": 0,
                "failed_actions": 0
            }
        }


class PlaybookListResponse(BaseModel):
    """Response model for listing playbooks"""
    total: int = Field(..., description="Total number of playbooks")
    page: int = Field(..., description="Current page number")
    page_size: int = Field(..., description="Number of playbooks per page")
    playbooks: List[Playbook] = Field(..., description="List of playbooks")
    
    class Config:
        json_schema_extra = {
            "example": {
                "total": 15,
                "page": 1,
                "page_size": 10,
                "playbooks": []
            }
        }


class PlaybookResponse(BaseModel):
    """Response model for single playbook retrieval"""
    playbook: Playbook = Field(..., description="The playbook object")
    
    class Config:
        json_schema_extra = {
            "example": {
                "playbook": {
                    "playbook_id": "playbook-550e8400",
                    "name": "Mitigate Brute Force Attack",
                    "status": "draft"
                }
            }
        }


class PlaybookCreateRequest(BaseModel):
    """Request model for creating playbooks (used by AI or manual creation)"""
    name: str
    description: str
    alert_id: str
    actions: List[Dict[str, Any]]
    generated_by: str = "manual"
    confidence_score: Optional[float] = None


class PlaybookApprovalRequest(BaseModel):
    """Request model for approving/rejecting playbooks"""
    approved: bool = Field(..., description="Whether to approve or reject")
    approved_by: str = Field(..., description="Username of approver")
    comments: Optional[str] = Field(None, description="Optional approval comments")
